{"name": "test_3", "status": "failed", "statusDetails": {"message": "AssertionError: assert 2 == 6\n  +2\n  -6", "trace": "setup_module = <Pytest.test_allure2.TestClass object at 0x000002C583A37EB0>\n\n    @allure.story(\"功能测试用例3\")\n    def test_3(setup_module):\n        print('Test_3 called.')\n>       assert 2 == 1 + 5\nE       assert 2 == 6\nE         +2\nE         -6\n\ntest_allure2.py:35: AssertionError"}, "start": 1643177332295, "stop": 1643177332296, "uuid": "eb215787-0fe4-4580-ab6a-753e3dd2e018", "historyId": "3cd3021efd2c9cdca6e71c38112d6732", "testCaseId": "c98b9fe8fa316bbd69ea874cb4139972", "fullName": "test_allure2.TestClass#test_3", "labels": [{"name": "feature", "value": "测试用例功能"}, {"name": "story", "value": "功能测试用例3"}, {"name": "suite", "value": "test_allure2"}, {"name": "subSuite", "value": "TestClass"}, {"name": "host", "value": "DESKTOP-V45JC51"}, {"name": "thread", "value": "5572-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_allure2"}]}